using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Text;
using EngineRoom.Generators.Helpers;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace EngineRoom.Generators.Dependency
{
    // Validation lives in DependencyAnalyzer; this generator silently skips any
    // input the analyzer would flag so its output never piles on top of a
    // compile error. The field type comes from syntax (not symbols) because
    // singleton interfaces are usually generated by SingletonGenerator and
    // therefore unresolved in this generator's compilation snapshot.
    [Generator(LanguageNames.CSharp)]
    public sealed class DependencyGenerator : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var fieldEntries = context.SyntaxProvider
                .ForAttributeWithMetadataName(
                    DependencyConstants.AttributeFullName,
                    predicate: static (node, _) => node is VariableDeclaratorSyntax,
                    transform: static (ctx, _) => ExtractFieldEntry(ctx))
                .Where(static entry => entry.HasValue)
                .Select(static (entry, _) => entry!.Value);

            context.RegisterSourceOutput(fieldEntries.Collect(), static (ctx, entries) => Emit(ctx, entries));
        }

        private static DependencyFieldEntry? ExtractFieldEntry(GeneratorAttributeSyntaxContext ctx)
        {
            if (ctx.TargetSymbol is not IFieldSymbol fieldSymbol)
            {
                return null;
            }

            if (ctx.TargetNode is not VariableDeclaratorSyntax declarator
                || declarator.Parent is not VariableDeclarationSyntax variableDeclaration
                || variableDeclaration.Parent is not FieldDeclarationSyntax
                || variableDeclaration.Parent.Parent is not ClassDeclarationSyntax classDeclaration)
            {
                return null;
            }

            if (!classDeclaration.Modifiers.Any(SyntaxKind.PartialKeyword))
            {
                return null;
            }

            if (fieldSymbol.ContainingType is not INamedTypeSymbol classSymbol)
            {
                return null;
            }

            if (!SymbolInspector.InheritsFrom(classSymbol, DependencyConstants.MonoBehaviourFullyQualifiedName))
            {
                return null;
            }

            var hasOwnStart = classSymbol.GetMembers("Start")
                .OfType<IMethodSymbol>()
                .Any(static method => method.MethodKind == MethodKind.Ordinary
                    && method.Parameters.Length == 0
                    && !method.IsStatic);
            if (hasOwnStart)
            {
                return null;
            }

            if (fieldSymbol.IsStatic)
            {
                return null;
            }

            if (fieldSymbol.DeclaredAccessibility != Accessibility.Private
                && fieldSymbol.DeclaredAccessibility != Accessibility.Protected)
            {
                return null;
            }

            var classNamespace = classSymbol.ContainingNamespace.IsGlobalNamespace
                ? null
                : classSymbol.ContainingNamespace.ToDisplayString();
            var classFullName = classSymbol.ToDisplayString(SymbolFormatter.FullyQualifiedType);
            var hintPrefix = classNamespace is null ? classSymbol.Name : classNamespace + "." + classSymbol.Name;

            // Pull the field type as text from the declaration so the assignment
            // compiles even when the interface comes from another generator —
            // the simple name resolves against the host class's namespace at
            // final-compile time, which is where singleton interfaces live.
            var fieldTypeText = variableDeclaration.Type.ToString();

            return new DependencyFieldEntry(
                classFullName: classFullName,
                @namespace: classNamespace,
                className: classSymbol.Name,
                hintPrefix: hintPrefix,
                fieldName: declarator.Identifier.Text,
                fieldTypeText: fieldTypeText);
        }

        private static void Emit(SourceProductionContext ctx, ImmutableArray<DependencyFieldEntry> entries)
        {
            if (entries.IsDefaultOrEmpty)
            {
                return;
            }

            // Group by class so a host with multiple [Dependency] fields gets a
            // single generated partial.
            var byClass = new Dictionary<string, List<DependencyFieldEntry>>();
            foreach (var entry in entries)
            {
                if (!byClass.TryGetValue(entry.ClassFullName, out var list))
                {
                    list = new List<DependencyFieldEntry>();
                    byClass[entry.ClassFullName] = list;
                }
                list.Add(entry);
            }

            foreach (var pair in byClass)
            {
                EmitClass(ctx, pair.Value);
            }
        }

        private static void EmitClass(SourceProductionContext ctx, List<DependencyFieldEntry> fields)
        {
            var first = fields[0];
            var assignments = string.Join(
                "\n",
                fields.Select(static field => field.FieldName + " = " + field.FieldTypeText + ".Instance;"));

            var body = TemplateLoader.LoadAndSubstitute("Dependency/DependencyPartial", new Dictionary<string, string>
            {
                ["ClassName"] = first.ClassName,
                ["Assignments"] = assignments,
            });

            var text = SourceFileBuilder.Build(body, first.Namespace);
            ctx.AddSource(first.HintPrefix + ".Dependency.Partial.g.cs", SourceText.From(text, Encoding.UTF8));
        }
    }
}
