using System.Collections.Generic;
using System.Linq;

namespace EngineRoom.Generators.Helpers
{
    // Block-scoped namespaces only — Unity's default C# language version doesn't
    // accept file-scoped ones.
    internal static class SourceFileBuilder
    {
        private const string FileHeader = "// <auto-generated/>\n#nullable enable\n\n";
        private const string NamespaceIndent = "    ";

        public static string Build(string typeBody, string? containingNamespace)
        {
            var body = containingNamespace is null
                ? typeBody
                : WrapInNamespace(typeBody, containingNamespace);

            return FileHeader + body;
        }

        private static string WrapInNamespace(string content, string containingNamespace)
        {
            var indented = string.Join("\n", content.Split('\n').Select(IndentNonEmpty));

            return TemplateLoader.LoadAndSubstitute("Namespace", new Dictionary<string, string>
            {
                ["Namespace"] = containingNamespace,
                ["Content"] = indented,
            });
        }

        // A templated placeholder line that became empty after substitution gets
        // collapsed to a true empty line — otherwise we'd emit trailing-whitespace
        // noise on every generated file.
        private static string IndentNonEmpty(string line)
        {
            var trimmed = line.TrimEnd();
            return trimmed.Length == 0 ? string.Empty : NamespaceIndent + trimmed;
        }
    }
}
